color: null
fieldLayouts:
  1b284879-9c39-4c13-b37c-f8bd42c4e051:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: df90413b-6505-477c-8885-52f99c7e4495
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8f798e34-dc2a-493a-a1fe-08585ddbafb2 # Matrix
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 483130a0-30d0-4320-a9dc-79bfa41e7112
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5a8bb032-988c-4d4c-a3dd-c38d9db27682
        userCondition: null
handle: pageType
hasTitleField: true
icon: ''
name: 'Page Type'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
