defaultPlacement: end
enableVersioning: true
entryTypes:
  - cd783400-11a4-4a03-8382-159a2ea04343 # Page Type
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  93396e6c-9e94-48dd-bf80-aac9577161d9: # Test
    enabledByDefault: true
    hasUrls: true
    template: home/_entry
    uriFormat: __home__
type: single
